CU-2wv5xwu_Tech_Manual
enphoria/ms-fault-location pull request #5
Opened 2022-06-16 02:30 UTC by Neoramses1984

tech manual

2022-06-16 02:30 UTC, Neoramses1984 commented
Task linked: [CU-2wv5xwu Realizar manual técnico de la calculadora fault location](https://app.clickup.com/t/2wv5xwu)

2022-06-21 00:14 UTC, cmacana requested changes

2022-06-21 04:55 UTC, Neoramses1984 reviewed
changes done

2022-06-21 04:55 UTC, Neoramses1984 commented on documentation/manual_tecnico.md
> -![logo_prueba](logo_enphoria.png "Logo Enphoria")
the image was changed for a new front page with all logos.

2022-06-21 04:55 UTC, Neoramses1984 commented on documentation/manual_tecnico.md
> -El método de localización de fallas que proponemos combina la información de la red del feeder junto con las mediciones de corriente para la posible localización de fallas. En primer lugar, el método
done

2022-06-21 04:55 UTC, Neoramses1984 commented on documentation/manual_tecnico.md
> -Un reconectador o un disyuntor aguas arriba de la falla se dispara cuando se produce una falla en una línea. El reconectador o el disyuntor disparado registra la magnitud RMS de la corriente de falla
done

2022-06-21 04:55 UTC, Neoramses1984 commented on documentation/manual_tecnico.md
> -Se realiza un rastreo aguas abajo del reconectador disparado o del disyuntor. El rastreo se detiene cuando se descubre un reconectador, un fusible o un disyuntor, o cuando se alcanza el final de la l
done

2022-06-21 04:55 UTC, Neoramses1984 commented on documentation/manual_tecnico.md
> -En esta sección se valida el algoritmo propuesto en diferentes feeders de redes de distribución de distribución en Nueva Gales del Sur (NSW), Australia. Los parámetros eléctricos como el voltaje de l
done

2022-06-21 04:55 UTC, Neoramses1984 commented on documentation/manual_tecnico.md
> -En esta sección se valida el algoritmo propuesto en diferentes feeders de redes de distribución de distribución en Nueva Gales del Sur (NSW), Australia. Los parámetros eléctricos como el voltaje de l
done

2022-06-21 04:55 UTC, Neoramses1984 commented on documentation/manual_tecnico.md
>  Se observa que alrededor del 50 por ciento de la falla se localiza con una expectativa de falla de 95-100 por ciento con el método propuesto. Aproximadamente el 12,5 por ciento de la falla se encuent
done

2022-06-21 04:55 UTC, Neoramses1984 commented on documentation/manual_tecnico.md
>  Se observa que alrededor del 50 por ciento de la falla se localiza con una expectativa de falla de 95-100 por ciento con el método propuesto. Aproximadamente el 12,5 por ciento de la falla se encuent
done

2022-06-21 04:55 UTC, Neoramses1984 commented on documentation/manual_tecnico.md
> +En esta sección se valida el algoritmo propuesto en diferentes feeders de redes de distribución de distribución en Nueva Gales del Sur (NSW), Australia. Los parámetros eléctricos como el voltaje de l
done

2022-06-21 05:06 UTC, Neoramses1984 commented
tech manual with corrections

2022-06-21 05:06 UTC, closed without merging